### ISSUE TITLE
Transfert : message d'erreur 

### ISSUE THREAD

**Issue by Delavy** [Delavy/simplechat#1]
Lorsque l'on envoie un fichier qui n'existe pas, il faudrait changer le message d'erreur de `ludo.txt n'est pas un fichier` à `ludo.txt n'existe pas`

**Comment by ludovicn** [comment]
Merci ! :P 
J'ai l'impression de me retrouver au boulot xD 

Je trouvais des bugs a la con xD

Cordialement,
--
Ludovic NIVOIX
Etudiant en Master Informatique
Téléphone : +33637886128

**Comment by ludovicn** [comment]
Le problème là est reglé

**Comment by ludovicn** [comment]
J'ai oublié de fermer cette issue, désolé !
